In [4]:
from google.colab import drive

drive.mount('/content/drive')


Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


In [5]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [6]:
dataset = pd.read_csv('/content/drive/MyDrive/Ml-datasets/Social_Network_svm.csv')
X = dataset.iloc[:, :-1].values
y = dataset.iloc[:, -1].values

In [7]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.25, random_state = 0)

In [8]:
from sklearn.preprocessing import StandardScaler, MinMaxScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

In [9]:
scaler = MinMaxScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

In [10]:
from sklearn.preprocessing import Binarizer
binarizer = Binarizer(threshold=0.5)
X_train = binarizer.fit_transform(X_train)
X_test = binarizer.transform(X_test)
print(X_train[:5])

[[1. 0.]
 [0. 1.]
 [0. 0.]
 [0. 1.]
 [1. 0.]]


In [11]:
print(X_train)

[[1. 0.]
 [0. 1.]
 [0. 0.]
 [0. 1.]
 [1. 0.]
 [1. 1.]
 [1. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [1. 0.]
 [1. 0.]
 [1. 0.]
 [1. 0.]
 [1. 1.]
 [0. 1.]
 [1. 0.]
 [1. 0.]
 [0. 0.]
 [1. 1.]
 [0. 1.]
 [1. 1.]
 [1. 0.]
 [0. 0.]
 [1. 0.]
 [1. 1.]
 [0. 1.]
 [0. 1.]
 [0. 0.]
 [1. 0.]
 [0. 0.]
 [1. 1.]
 [1. 1.]
 [0. 0.]
 [1. 1.]
 [0. 1.]
 [1. 0.]
 [1. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [1. 0.]
 [0. 0.]
 [0. 1.]
 [1. 0.]
 [1. 1.]
 [1. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [1. 1.]
 [0. 0.]
 [1. 0.]
 [1. 0.]
 [0. 0.]
 [1. 1.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [1. 1.]
 [0. 0.]
 [0. 1.]
 [1. 0.]
 [0. 1.]
 [0. 1.]
 [0. 1.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [1. 0.]
 [0. 1.]
 [1. 1.]
 [0. 1.]
 [0. 0.]
 [1. 1.]
 [1. 0.]
 [0. 0.]
 [0. 1.]
 [0. 1.]
 [1. 0.]
 [1. 0.]
 [1. 1.]
 [0. 0.]
 [0. 0.]
 [1. 1.]
 [1. 0.]
 [0. 0.]
 [0. 1.]
 [1. 1.]
 [1. 0.]
 [0. 0.]
 [1. 0.]
 [1. 0.]
 [1. 0.]
 [1. 0.]
 [0. 1.]
 [0. 0.]
 [1. 0.]
 [1. 1.]
 [1. 0.]
 [1. 0.]
 [1. 1.]
 [1. 1.]
 [0. 0.]
 [1. 1.]
 [1. 0.]
 [0. 0.]
 

In [12]:
dataset.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 400 entries, 0 to 399
Data columns (total 3 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Age              400 non-null    int64
 1   EstimatedSalary  400 non-null    int64
 2   Purchased        400 non-null    int64
dtypes: int64(3)
memory usage: 9.5 KB


In [13]:
dataset.describe()

Age  EstimatedSalary   Purchased
count  400.000000       400.000000  400.000000
mean    37.655000     69742.500000    0.357500
std     10.482877     34096.960282    0.479864
min     18.000000     15000.000000    0.000000
25%     29.750000     43000.000000    0.000000
50%     37.000000     70000.000000    0.000000
75%     46.000000     88000.000000    1.000000
max     60.000000    150000.000000    1.000000

# Feature Selection For Machine
Learning

1.  Univariate Selection

In [14]:
#from sklearn.feature_selection import SelectKBest, f_classif
#selector = SelectKBest(score_func=f_classif, k=2)
#X_new = selector.fit_transform(X_train, y_train)

#print("Feature Scores:", selector.scores_)

#print("Selected Features Shape:", X_new.shape)


2.Recursive Feature Elimination

In [15]:
from sklearn.feature_selection import RFE
from sklearn.svm import SVC

model = SVC(kernel="linear")
rfe = RFE(model, n_features_to_select=2)
X_new = rfe.fit_transform(X_train, y_train)

print("Feature Ranking:", rfe.ranking_)

print("Selected Features Shape:", X_new.shape)


Feature Ranking: [1 1]
Selected Features Shape: (300, 2)


3. Principal Component Analysis

In [16]:
from sklearn.decomposition import PCA
pca = PCA(n_components=2)
X_new = pca.fit_transform(X_train)

print("Explained Variance Ratio:", pca.explained_variance_ratio_)
print("Selected Features Shape:", X_new.shape)


Explained Variance Ratio: [0.56531141 0.43468859]
Selected Features Shape: (300, 2)


4.Feature Importance

In [17]:
from sklearn.ensemble import ExtraTreesClassifier

model = ExtraTreesClassifier()
model.fit(X_train, y_train)

print("Feature Importances:", model.feature_importances_)


Feature Importances: [0.53081532 0.46918468]


# Evaluate the Performance of Machine Learning Algorithms with Resampling
    

1. K-Fold Cross Validation

In [18]:
from sklearn.model_selection import train_test_split, cross_val_score, KFold, LeaveOneOut, RepeatedStratifiedKFold
# k = 10
# kf = KFold(n_splits=k, shuffle=True, random_state=0)
# model = SVC(kernel='linear')

# scores = cross_val_score(model, X, y, cv=kf)

# print(f"K-Fold Cross Validation Scores: {scores}")
# print(f"Mean Accuracy: {np.mean(scores):.4f}")


2.Leave-One-Out Cross Validation

In [19]:
loo = LeaveOneOut()
scores = cross_val_score(model, X, y, cv=loo)

print(f"LOOCV Accuracy: {np.mean(scores):.4f}")


LOOCV Accuracy: 0.8725


3.Repeated Random Test-Train Splits

In [20]:
repeated_kf = RepeatedStratifiedKFold(n_splits=10, n_repeats=3, random_state=0)

scores = cross_val_score(model, X, y, cv=repeated_kf)

print(f"Repeated Holdout Accuracy Scores: {scores}")
print(f"Mean Accuracy: {np.mean(scores):.4f}")


Repeated Holdout Accuracy Scores: [0.825 0.85  0.9   0.8   0.925 0.9   0.95  0.9   0.825 0.9   0.9   0.925
 0.925 0.9   0.875 0.9   0.825 0.975 0.75  0.85  0.925 0.8   0.925 0.85
 0.85  0.9   0.925 0.95  0.875 0.875]
Mean Accuracy: 0.8825


# Machine Learning Algorithm Performance Metrics

1.Classification Metrics

In [21]:
from sklearn.svm import SVC
from sklearn.metrics import accuracy_score, log_loss, roc_auc_score, confusion_matrix, classification_report

model = SVC(kernel='linear', probability=True)
model.fit(X_train, y_train)
y_pred = model.predict(X_test)
y_pred_prob = model.predict_proba(X_test)

accuracy = accuracy_score(y_test, y_pred)
logloss = log_loss(y_test, y_pred_prob)
roc_auc = roc_auc_score(y_test, y_pred_prob[:, 1])
conf_matrix = confusion_matrix(y_test, y_pred)
class_report = classification_report(y_test, y_pred)

print(f"Classification Accuracy: {accuracy:.4f}")
print(f"Logarithmic Loss: {logloss:.4f}")
print(f"Area Under ROC Curve: {roc_auc:.4f}")
print("Confusion Matrix:")
print(conf_matrix)
print("Classification Report:")
print(class_report)

Classification Accuracy: 0.7300
Logarithmic Loss: 0.5552
Area Under ROC Curve: 0.7022
Confusion Matrix:
[[53 15]
 [12 20]]
Classification Report:
              precision    recall  f1-score   support

           0       0.82      0.78      0.80        68
           1       0.57      0.62      0.60        32

    accuracy                           0.73       100
   macro avg       0.69      0.70      0.70       100
weighted avg       0.74      0.73      0.73       100



2. Regression Tasks

In [22]:
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score

mae = mean_absolute_error(y_test, y_pred)
mse = mean_squared_error(y_test, y_pred)
r2 = r2_score(y_test, y_pred)

print(f"Mean Absolute Error: {mae:.4f}")
print(f"Mean Squared Error: {mse:.4f}")
print(f"R2 Score: {r2:.4f}")


Mean Absolute Error: 0.2700
Mean Squared Error: 0.2700
R2 Score: -0.2408
